#ifndef LNG_HPP_A5DED539_88BF_4605_9A46_F2D47A6D9F7C
#define LNG_HPP_A5DED539_88BF_4605_9A46_F2D47A6D9F7C
#pragma once

namespace spotifar
{
    enum
    {
        MPluginUserName,

        MOk,
        MCancel,
        MYes,
        MShowLogs,
        MRelaunch,
        MLike,
        MUnlike,

        // sorting-related
        MSortDlgTitle,
        MSortColName,
        MSortColExplicit,
        MSortColDuration,
        MSortColYear,
        MSortColRelease,
        MSortColArtist,
        MSortColPopularity,
        MSortColAlbum,
        MSortColType,
        MSortColSaved,
        MSortColTrackNum,
        MSortColTrackMultiNum,
        MSortColPlayedAt,
        MSortColSavedAt,
        MSortColAddedAt,
        MSortColDescr,
        MSortColTracksCount,
        MSortColOwner,
        MSortColIsPublic,
        MSortColIsColab,
        MSortColFollow,
        MSortColGenre,
        MSortColAlbumsCount,
        MSortColCopyrights,
        
        MSortBarName,
        MSortBarRelease,
        MSortBarPopularity,
        MSortBarAlbum,
        MSortBarArtist,
        MSortBarDuration,
        MSortBarTrackNum,
        MSortBarPlayedAt,
        MSortBarSavedAt,
        MSortBarUnsorted,
        MSortBarAddedAt,
        MSortBarTracksCount,
        MSortBarOwner,
        MSortBarFollow,

        // config menu
        MCfgDlgMenuTitle,
        MCfgDlgMenuGeneral,
        MCfgDlgMenuBackend,
        MCfgDlgMenuHotkeys,
        MCfgDlgMenuCaches,

        // general configuration dialog
        MCfgGeneralBoxTitle,
        MCfgAddToDisksMenu,
        MCfgVerboseLog,
        MCfgSpotifyTitle,
        MCfgSpotifyClientID,
        MCfgSpotifyClientSecret,
        MCfgLocalhostServicePort,
        MCfgNotificationsTitle,
        MCfgTrackChanged,
        MCfgImageShape,
        MCfgImageShapeSquare,
        MCfgImageShapeCircle,

        // playback configuration dialog
        MCfgPlayback,
        MCfgNormalisation,
        MCfgAutoplay,
        MCfgGapless,
        MCfgCache,
        MCfgBitrate,
        MCfgFormat,
        MCfgDither,
        MCfgVolumeCtrl,

        // hotkeys configuration dialog
        MCfgHotkeys,
        MCfgHotkeysTable,
        MCfgPlayPause,
        MCfgSkipToNext,
        MCfgSkipToPrev,
        MCfgSeekForward,
        MCfgSeekBackward,
        MCfgVolumeUp,
        MCfgVolumeDown,
        MCfgShowToast,

        // caches & logs configuration dialog
        MCfgLogs,
        MCfgLogsCount,
        MCfgLogsFolderSize,
        MCfgShowLogsBtn,
        MCfgClearLogsBtn,
        MCfgCaches,
        MCfgCredentials,
        MCfgCredentialsClearBtn,
        MCfgHttpCache,
        MCfgHttpCacheClearBtn,
        MCfgClearAllCaches,
        MCfgReleases,
        MCfgReleasesSyncStatus,
        MCfgReleasesStatusFinished,
        MCfgReleasesStatusLeft,
        MCfgReleasesResyncBtn,

        // panlels & ui
        MPanelCollection,
        MPanelCollectionDescr,
        MPanelArtists,
        MPanelArtistsDescr,
        MPanelAlbums,
        MPanelAlbumsDescr,
        MPanelTracks,
        MPanelTracksDescr,
        MPanelAlbum,
        MPanelAlbumDescr,
        MPanelArtist,
        MPanelArtistDescr,
        MPanelPlaylists,
        MPanelPlaylistsItemDescr,
		MPanelRecents,
		MPanelRecentsDescr,
		MPanelPlayingQueue,
		MPanelPlayingQueueDescr,
		MPanelRecentTracks,
		MPanelRecentTracksDescr,
		MPanelRecentAlbums,
		MPanelRecentAlbumsDescr,
		MPanelRecentArtists,
		MPanelRecentArtistsDescr,
		MPanelRecentPlaylists,
		MPanelRecentPlaylistsDescr,
		MPanelNewReleases,
		MPanelNewReleasesDescr,
		MPanelBrowse,
		MPanelBrowseDescr,
		MPanelRecentlySaved,
		MPanelRecentlySavedDescr,
		MPanelRecentlyLikedTracks,
		MPanelRecentlyLikedTracksDescr,
		MPanelRecentlySavedAlbums,
		MPanelRecentlySavedAlbumsDescr,
		MPanelUserTopItems,
		MPanelUserTopItemsDescr,
		MPanelUserTopArtists,
		MPanelUserTopArtistsDescr,
		MPanelUserTopTracks,
		MPanelUserTopTracksDescr,
		MPanelArtistTopTracks,
		MPanelArtistTopTracksDescr,

        MPlayerSourceLabel,
        MPlayerSourceCollection,
        MPlayerRepeatNoneBtn,
        MPlayerRepeatOneBtn,
        MPlayerRepeatAllBtn,
        MPlayerShuffleBtn,

        // spotify specifics
        MArtistUnknown,
        MGenreUnknown,
        MCopyrightUnknown,

        // warnings & errors
        MFarMessageWarningTitle,
        MFarMessageErrorTitle,
        MErrorPluginStartupUnexpected,
        MErrorPluginStartupNoClientID,
        MErrorPluginStartupNoClientSecret,
        MErrorLibrespotStartupUnexpected,
        MErrorLibrespotStoppedUnexpectedly,
        MErrorWinToastStartupUnexpected,
        MErrorSyncThreadFailed,
        MErrorPlaybackCmdFailed,
        MErrorCollectionFetchFailed,
        MErrorConfigMigrationError,
        MErrorRemoveFile,

        // notifications
        MToastNewReleasesFoundTitle,
        MToastNewReleasesFoundHaveALookBtn,
        MToastSpotifyAttibution,
        MToastTrackChangedLikeBtn,
        MToastTrackChangedUnlikeBtn,
        MToastTrackChangedNextBtn,

        // complimentary dialogs & menus
        MTransferPlaybackTitle,
        MTransferPlaybackMessage,
        MTransferPlaybackInactiveMessage01,
        MTransferPlaybackInactiveMessage02,
        MTransferNoAvailableDevices,
        MWaitingRequest,
        MWaitingItemsProgress,
        MWaitingInitSpotify,
        MWaitingInitSyncWorker,
        MWaitingInitLibrespot,
        MWaitingFiniSpotify,
        MWaitingFiniSyncWorker,
        MWaitingFiniLibrespot,
    };
}

#endif // LNG_HPP_A5DED539_88BF_4605_9A46_F2D47A6D9F7C