name: Releases

on:
  push:
    branches: [main]

jobs:
  build-librespot:
    uses: ./.github/workflows/build-librespot.yml
    permissions:
      actions: read
      contents: read
    with:
      profile: 'xRelease'
      caching: false # no caching used for master releases
    secrets: inherit

  build-spotifar:
    uses: ./.github/workflows/build-library.yml
    permissions:
      actions: read
      contents: read
    needs: build-librespot
    with:
      build_type: 'Release'
      build_librespot: false
      caching: false # no caching used for master releases
    secrets: inherit