name: Releases

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # build-librespot:
  #   uses: ./.github/workflows/build-librespot.yml
  #   permissions:
  #     actions: read
  #     contents: read
  #   with:
  #     profile: 'xRelease'
  #     caching: false # no caching used for master releases
  #   secrets: inherit

  # build-spotifar:
  #   uses: ./.github/workflows/build-library.yml
  #   permissions:
  #     actions: read
  #     contents: read
  #   needs: build-librespot
  #   with:
  #     build_type: 'Release'
  #     build_librespot: false
  #     testing: false
  #     caching: false # no caching used for master releases
  #   secrets: inherit


  packaging:
    # needs: [build-librespot, build-spotifar]
    runs-on: windows-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version and label
        id: get_version
        run: |
          $version = (Select-String -Path CMakeLists.txt -Pattern 'project\(.*VERSION ([0-9\.]+)').Matches[0].Groups[1].Value
          $tag = git tag --sort=-taggerdate
          if (-not $tag) { $build_num = 0 }
          else { $build_num = [int]($tag.Split('.')[-1]) }
          $next_build_num = $build_num + 1
          $full_version = "$version.$next_build_num"
          $new_tag_name = "v$full_version"
          echo "tag=$new_tag_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts
          pattern: spotifar-*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          name: Spotifar ${{ steps.get_version.outputs.tag }}
          files: artifacts/**/*
          generate_release_notes: true